- name: setup build environment for xrootd
  hosts: localhost
  vars:
    xrootd_version: 5.5.1
    xrootd_repo: https://github.com/xrootd/xrootd.git
    xrootd_branch: v5.5.x
    ckslib_repo: https://github.com/alex-rg/xrd_ckslib.git
    ckslib_branch: calc_adler32
    ckslib_version: 0.1
    ckslib_release: 1
    rpmbuild_home: "{{ansible_env.HOME}}/rpmbuild"
  tasks:
  - name: clean old build
    command:
      cmd: rm -rf "{{rpmbuild_home}}"
  - name: install devtoolset
    yum:
      name: "{{'devtoolset-7' if ansible_distribution == 'CentOS' else 'gcc-toolset-9'}}"
      state: present
  - name: install rpmbuild
    yum:
      name: rpm-build
      state: present
  - name: create rpmbuild directories
    file:
      path: "{{rpmbuild_home}}{{item}}"
      state: directory
    loop: [ '', '/RPMS', '/SOURCES', '/SRPMS', '/BUILD', '/BUILDROOT', '/SPECS']
  - name: create dir for source file
    file:
      path: "{{rpmbuild_home}}/tmp"
      state: directory
  - name: clone ckslib repository
    command:
      cmd: git clone -b "{{ckslib_branch}}" "{{ckslib_repo}}" .
      chdir: "{{rpmbuild_home}}/tmp"
  - name: create source file
    shell:
      cmd: git archive "{{ckslib_branch}}" > "{{rpmbuild_home}}/SOURCES/xrdckslib.tar.gz"
      chdir: "{{rpmbuild_home}}/tmp"
  - name: render spec template
    template:
      src: "{{playbook_dir}}/packaging/CksLib.spec"
      dest: "{{rpmbuild_home}}/SPECS/CksLib.spec"
  - name: build rpm
    shell:
      cmd: source /opt/rh/devtoolset-7/enable && rpmbuild -ba "{{rpmbuild_home}}/SPECS/CksLib.spec"
